### ISSUE TITLE
After updating 5.4.5 to 6.x rocket server don't start

### ISSUE THREAD

**Issue by CvH** [RocketChat/rocketchat-server-snap#55]
updated description

After updating rocket snaps from 5.4.x to 6.1.x the rocket server won't start anymore. Looks like a mongo db problem.

```snap.rocketchat-server.rocketchat-server.service: Scheduled restart job, restart counter is at 50.
Stopped Service for snap application rocketchat-server.rocketchat-server.
snap.rocketchat-server.rocketchat-server.service: Consumed 2.357s CPU time.
Started Service for snap application rocketchat-server.rocketchat-server.
node $SNAP/main.js
/snap/rocketchat-server/1546/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
errorClass [Error]: [An error occurred when creating an index for collection "users: An equivalent index already exists with the same name but different options. Requested index: { v: 2, unique: true, key: { username: 1 }, name: "username_1", sparse: true }, existing index: { v: 2, unique: true, key: { username: 1 }, name: "username_1", ns: "parties.users", sparse: 1 }]
    at Collection.createIndex (packages/mongo/collection.js:801:15)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1776:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:75:5)
    at packages/accounts-base/server_main.js:7:12
    at module (packages/accounts-base/server_main.js:19:31)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /snap/rocketchat-server/1546/programs/server/packages/accounts-base.js:2192:15
    at /snap/rocketchat-server/1546/programs/server/packages/accounts-base.js:2199:3
    at /snap/rocketchat-server/1546/programs/server/boot.js:369:38
    at Array.forEach (<anonymous>)
    at /snap/rocketchat-server/1546/programs/server/boot.js:210:21
    at /snap/rocketchat-server/1546/programs/server/boot.js:423:7
    at Function.run (/snap/rocketchat-server/1546/programs/server/profile.js:256:14)
    at /snap/rocketchat-server/1546/programs/server/boot.js:422:13 {
  isClientSafe: true,
  error: 'An error occurred when creating an index for collection "users: An equivalent index already exists with the same name but different options. Requested index: { v: 2, unique: true, key: { username: 1 }, name: "username_1", sparse: true }, existing index: { v: 2, unique: true, key: { username: 1 }, name: "username_1", ns: "parties.users", sparse: 1 }',
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
pkill: pidfile not valid
Try `pkill --help' for more information.
snap.rocketchat-server.rocketchat-server.service: Control process exited, code=exited, status=1/FAILURE
snap.rocketchat-server.rocketchat-server.service: Failed with result 'exit-code'.
snap.rocketchat-server.rocketchat-server.service: Consumed 2.338s CPU time.```

**Comment by CvH** [comment]
was confused with the caddy server, turns out it looks like a mongo db problem :( (updated first post accordingly)

**Comment by CvH** [comment]
still the same problem for 6.1.6

**Comment by CvH** [comment]
Isn't a fix but a dirty workaround for making it work from https://github.com/RocketChat/Rocket.Chat/issues/29167.

Stop RC Server
> systemctl stop snap.rocketchat-server.rocketchat-server.service

For Ubuntu 20.04 install Mongodb client (`rocketchat-server.mongo` is broken for a while)
> apt install mongodb-clients

Connect to the Mongodb and remove the user index.
> mongo

> use parties
> db.users.dropIndexes()

reboot server
> reboot
