### ISSUE TITLE
Cannot restore renamed collections 

### ISSUE THREAD

**Issue by manidharkakarla** [RocketChat/rocketchat-server-snap#60]
I have rocketchat 4.0 version in my old server. 
I took new instance and installed 6.0 version. 
I took backup from my old sever using dump 
I need to restore those folders in new server while restoring some collections are missing or renamed when the application is updated.
How can i overcome this problem

**Comment by vamsikurimeti** [comment]
@debdutdeb can you please help on this issue

**Comment by vamsikurimeti** [comment]
@geekgonecrazy @Sing-Li @rodrigok @brunobcestari @jcbrtl @r0zbot @d-gubert @casalsgh @marceloschmidt @salvadorgiovani 
any one please look in to this issue and help us to resolve as soon as possible

**Comment by geekgonecrazy** [comment]
Not enough information to even begin guessing.  I'll need logs of the actual mongo restore to see what succeeded and failed


Reminder that tagging a bunch of people and asking for support is typically considered bad form in open source.

**Comment by manidharkakarla** [comment]
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at mkdir (internal/fs/promises.js:533:10)
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at server/lib/dataExport/exportRoomMessagesToFile.ts:260:8
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:  => awaited here:
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at server/lib/dataExport/exportRoomMessagesToFile.ts:260:2
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:  => awaited here:
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at server/lib/dataExport/processDataDownloads.ts:181:22
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]:   code: 'ERR_INVALID_ARG_TYPE'
Aug 25 12:04:15 ip-10-0-26-168 rocketchat[401]: }

These are the logs

**Comment by debdutdeb** [comment]
That's a different error than what is mentioned above. Please share the output of the restore action as that is more relatable to what is posted above.

**Comment by manidharkakarla** [comment]
Please tell me how to resolve this error.
The restore action was successfully done 
But the old collection name is created as new collection where the old collection is not present in new version of rocketchat

**Comment by manidharkakarla** [comment]
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]: === UnHandledPromiseRejection ===
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]: TypeError: Cannot read property 'getRedirectURL' of undefined
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]:     at app/file-upload/server/config/AmazonS3.ts:16:35
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]: ---------------------------------
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]: Errors like this can cause oplog processing errors.
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]: Future node.js versions will automatically exit the process
Aug 25 12:03:32 ip-10-0-26-168 rocketchat[401]: =================================

These are existing logs of rocketchat

**Comment by manidharkakarla** [comment]
what nodejs version did u used in latest rocketchat

**Comment by manidharkakarla** [comment]
Hello anyone please help
